version: 2

build:
  os: ubuntu-22.04

  tools:
    python: "3.11"

  jobs:
    post_install:
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - curl -LsSf https://astral.sh/uv/0.6.6/install.sh | sh
      - PATH="$HOME/.local/bin/env:$PATH" && VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs

mkdocs:
  configuration: mkdocs.yml
