version: 2

build:
  os: ubuntu-22.04

  tools:
    python: "3.11"

  jobs:
    post_create_environment:
      - curl -LsSf https://astral.sh/uv/0.7.3/install.sh | sh
    post_install:
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - PATH="/home/docs/.local/bin:$PATH" && VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs --active --link-mode=copy

mkdocs:
  configuration: mkdocs.yml
